- _episodes/04-built-in.md
> Add missing solution for episode 4

- _episodes/06-libraries.md
> Add missing solution for Episode 6

- _episodes/14-writing-functions.md
> Add missing solution for Episode 14

- _episodes/11-lists.md
Besides putting in solutions to challenges, this should fix a couple major formatting/markup errors in the lesson 
Fixes #11
> Added solutions to challenges and fixed lesson formatting errors

- _episodes/02-variables.md
- _episodes/03-types-conversion.md
- _episodes/11-lists.md
- _episodes/14-writing-functions.md
- _episodes/15-scope.md
- _episodes/17-conditionals.md
Apologies for the many individual commits. Each time I rationalised this with "Ah, it's not worth cloning & opening in Atom". It seems it would have been m-)
> Proof-read

- CONTRIBUTING.md
- _episodes/01-getting-started.md
- _episodes/14-writing-functions.md
- _episodes/15-scope.md
- bin/lesson_initialize.py
- index.md
- setup.md
See diff ;-) Because Anaconda's download page auto-detects the visitor's OS, we
don't need to maintain 3 different links here.
follow-up to https://github.com/data-lessons/library-python/pull/50
> Reflect Anaconda & macOS rebrandings

- _episodes/04-built-in.md
- _episodes/06-libraries.md
See diff ;-) Was probably left over from original, non-LC examples
.
> Correct variables

- _episodes/15-scope.md
Added solutions to the challenges
Fixes #14
> Implemented solutions to the challenges for Episode 15

- _episodes/11-lists.md
> Proof read some more

- aio.md
- setup.md
See diff & swcarpentry/r-novice-inflammation/issues/377 ;-)
> Repair asset loading on AIO & setup page

- README.md
> Correct 404 link in README

- README.md
Adding a note warning about our redesign efforts.
> adding status note about redesign

- README.md
And to #50 ;-) I missed this initially, sorry.
> Repair outdated homepage link (supplement to #48)

- _episodes/02-variables.md
- _episodes/11-lists.md
- _episodes/12-for-loops.md
It's library carpentry after all :D
> Change 'lab' to 'library'

- _episodes/17-conditionals.md
Hi,
I added solutions to 17-conditionals as mentioned in issue #15 
I've checked formatting via a local jekyll install and double checked the solutions to make sure they are correct.
Ted
> adding solutions to 17-conditionals.md

- _episodes/18-style.md
> Add solutions for Episode 18 

- _episodes/12-for-loops.md
> Add solution for Episode 12 For Loops - Reversing a String

- _episodes/17-conditionals.md
1) changed for loop variable to verbose -  pep8 (Always try to use the most concise but descriptive names possible) 
2) proposed slight language change for the print statement. conditional test is for larger/smaller, not large/small. Seems consistent to use reflective terms.
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions …
> verbose variable names and print statement

- _episodes/19-wrap.md
Same as https://github.com/swcarpentry/python-novice-gapminder/pull/443 ;-)
> Link to popular StackOverflow questions, not newest

- setup.md
Please delete the text below before submitting your contribution. 
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact Kate Hertweck …
> Updated spyder references spyder spyder-install

- _episodes/12-for-loops.md
> Fix cumulative sum task

- _episodes/01-getting-started.md
this will help me transition this lesson to the workbench. See https://github.com/carpentries/lesson-transition/issues/66
> remove stray "python" tag

- _config.yml
This is a fix to address https://github.com/carpentries/lesson-transition/issues/66
> remove old email config tag

- index.md
The PR adds a callout to the homepage of the lesson to note that the lesson will be replaced in early 2024.
> Add callout about redesign

- .zenodo.json
Updated list of authors and editors to reflect the last year of contributions and to prepare for a new release for Zenodo. Also re-ordered json authors alphabetically, following @tobyhodges recommendation.
> update zenodo editors and authors

- CITATION
- README.md
Adding updated zenodo link with current release and citation to readme file
> Add citation to readme

- episodes/getting-started.md
Trying to make more SMART objectives that use Blooms verbs.
> rewriting the episode LOs for getting-started.md
