LibraryCarpentry/lc-python-intro

_episodes/02-variables.md

["atom name" is rarely used](https://en.wikipedia.org/wiki/Special:Search?go=Go&search=%22atom+name%22). Since both strings denote chemical elements, please consider this renaming suggestion. Cheers :-)

Rename variable to scientific term

---

_episodes/02-variables.md

Hello :-)   How do you feel about renaming the example variable `last_name` into something entirely different, so that there is no risk of confusing it with Python's use of `name...`?
I am preparing to teach this lesson; that's why I noticed this possible issue. If it was chosen intentionally to then talk about Python's use of `name...`, please let me know.

Prevent confusion of Python's and our use of "name"

---

README.md

Should have been done as part of #5, my bad.
Also fix the clone URL to *not* be the main repo

Add reference to local Jekyll server

---

_episodes/19-wrap.md

See diff ;-) Without the protocol part, Jekyll prepends the page's own URL to the domain name (e.g. https://librarycarpentry.github.io/lc-python-intro/19-wrap/pycon.org/)

Repair hyperlinks

---

_episodes/06-libraries.md
_episodes/18-style.md
_includes/links.md

Sorry about these two changes at once. Am a bit too pressed for time.
The links aren't completely broken, because PyPI does server-side redirects after all. If you want to discuss the challenge change, we can do this after the Marburg workshop. This PR **doesn't have to be merged in time for Marburg**, though.

Update PyPi domain & "Import Libraries" challenge

---

index.md

The link on the index page is a 404 because of the trailing slash

fix setup link

---

_episodes/11-lists.md

Fix an error in the Working With the End exercise.
If a string has N elements, the most negative index that can be safely used is -N not -(N-1), corresponding to the [0] index.
>>> element = 'helium'
>>> print(element[-1])
m
>>> N = len(element)
>>> print(N)
6
>>> print(element[-(N-1)]) #This will give us the [1] index (e)
e
>>> print(element[-(N)])
h

Update 11-lists.md Working With the End exercise

---

_episodes/11-lists.md

_end_ has to be larger than _start_ - if it's smaller and a valid index, then an empty string will be returned, not the final element of the string

Correct "Slice bounds"

---

_episodes/01-getting-started.md
_extras/about.md
_extras/design.md
_extras/discuss.md
_extras/exercises.md
_extras/figures.md
_extras/guide.md
index.md
reference.md
setup.md

See discussion here for more background: https://github.com/datacarpentry/datacarpentry.github.io/issues/542
In short, some Carpentries lessons use the path `/guide/` for their Instructor Notes page and others use `/guide/index.html` (the default defined in `_config.yml`). This PR removes permalinks with a trailing slash from the YAML front matter of the Instructor Notes (`_extras/guide.md`) and other Extras files, consistent with new lessons created with [the lesson template](https://github.com/carpentries/styles/). Although there's no functional difference in the online versions of the lesson pages, pages with a trailing slash in the permalink will result in **broken links in the version of the lesson built locally**. We'd like local builds to be usable e.g. in workshops taking place at …

make lesson suitable for teaching with locally-built (serverless) pages

---

config.yaml

This adjusts the life cycle stage to flag up the development state of the lesson to page visitors. It will make the 'Alpha' banner appear at the top of the lesson pages.

Adjust life cycle configuration

---

index.md

Moved a note about the revised lesson to instructor notes and removed the callout drawing attention to the upcoming PR.

replace update notice

---

episodes/for-loops.md

In order to reinforce the introduction of append in the earlier lists episode, it might be smart to use it here and take advantage of the mutability of lists, rather than just re-creating the whole list.
The `print(odds)` line is optional and could be removed. It was added to reinforce visually the contents of the list after the append functions.

Use append instead of re-assigning full list

---

episodes/tidy.md

Replace the h1 (`#`) in line 19 with an h2 (`##`). It appears that having an h1 prevents the automated display of h2 titles in the navigation pane at the left side of the lesson and this change should resolve the issue.
Correct behavior:
Current behavior:

Remove h1 in tidy.md

---

episodes/getting-started.md

Closes #126
Provides background on the `$` prompt for Mac and Windows instructions on launching Jupyter Lab.

intro $ for command prompts

---

index.md

Noticed we are missing lesson level learning objects and took a stab at writing one for each episode. Please edit and refine. See: https://carpentries.github.io/lesson-development-training/objectives.html

Adding lesson learning objectives

---

learners/setup.md

Closes #130.
Converts the setup instructions to use[ tabbed callouts from the Workbench](https://carpentries.github.io/sandpaper-docs/component-guide.html#tabbed-callouts).

add tabbed install instructions

---

episodes/data-visualisation.md

add pandas bug note

---

episodes/getting-started.md

The original instructions launched jupyterlab in Windows users home directories which created issues when they start working with the data in the `lc-python` directory.

fix windows startup instructions

---

episodes/data-visualisation.md

I am using just an install of JupyterLab, not through Anaconda, and I needed to also install `ipywidgets` for Plotly to work. This is mentioned in their documentation: https://plotly.com/python/getting-started/#jupyterlab-support
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
I am using just an install of JupyterLab, not through Anaconda, and I needed to also install `ipywidgets` for Plotly to work. This is mentioned in [their documentation](https://plotly.com/python/getting-started/#jupyterlab-support). When I initially ran the Plotly plots, they were just blank boxes.
_If any relevant discussions have …

Add ipywidgets install for plotly

---

episodes/tidy.md

The DataFrame without the changes made to it was passed `to_pickle`, causing the user to save the wrong data in the file.
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
The DataFrame without the changes made to it was passed `to_pickle`, causing the user to save the wrong data in the file. When I did this and then read the pickle in the next episode, I had loaded the wrong data.
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) …

Reference correct DataFrame in `to_pickle`

---

episodes/writing-functions.md

The `else` statement used a redundant calculation that is the same as multiplying the days by `0.75`.
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
The `else` statement used a redundant calculation that is the same as multiplying the days by `0.75`. I found this confusing when going through the tutorial, as I was searching for some reason that the variable was multiplied twice, thinking I was missing something.
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the …

Clarify overdue fine function

---

episodes/libraries.md

The numbers in the textual description did not match with those from the output of `df_2011.info()`.
_If this pull request addresses an open issue on the repository, please add 'Closes #NN' below, where NN is the issue number._
_Please briefly summarise the changes made in the pull request, and the reason(s) for making these changes._
The numbers in the textual description did not match with those from the output of `df_2011.info()`. I updated them to match with what is displayed in your output, which is also what I got in my output when going through the course.
_If any relevant discussions have taken place elsewhere, please provide links to these._
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) …

Fix typos in libraries.md
